IMPORTING THE LIBRARIES

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df=pd.read_csv(r"C:\Users\saile\Downloads\housing_price_dataset.csv")

In [9]:
df

SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]

In [10]:
df.to_csv("House_Price_prediction_dataset")

In [11]:
df.dtypes

SquareFeet        int64
Bedrooms          int64
Bathrooms         int64
Neighborhood     object
YearBuilt         int64
Price           float64
dtype: object

In [12]:
df.info

<bound method DataFrame.info of        SquareFeet  Bedrooms  Bathrooms Neighborhood  YearBuilt          Price
0            2126         4          1        Rural       1969  215355.283618
1            2459         3          2        Rural       1980  195014.221626
2            1860         2          1       Suburb       1970  306891.012076
3            2294         2          1        Urban       1996  206786.787153
4            2130         5          2       Suburb       2001  272436.239065
...           ...       ...        ...          ...        ...            ...
49995        1282         5          3        Rural       1975  100080.865895
49996        2854         2          2       Suburb       1988  374507.656727
49997        2979         5          3       Suburb       1962  384110.555590
49998        2596         5          2        Rural       1984  380512.685957
49999        1572         5          3        Rural       2011  221618.583218

[50000 rows x 6 columns]>

# DATA PREPROCESSING

## EDA

In [13]:
df.isna().sum()

SquareFeet      0
Bedrooms        0
Bathrooms       0
Neighborhood    0
YearBuilt       0
Price           0
dtype: int64

In [14]:
df.duplicated().sum()

0

In [15]:
df["Neighborhood"]=df["Neighborhood"].map({"Rural":1,"Suburb":2,"Urban":3})

In [16]:
df.head()

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626
2        1860         2          1             2       1970  306891.012076
3        2294         2          1             3       1996  206786.787153
4        2130         5          2             2       2001  272436.239065

# MODEL BUILDING


## splitting into input and output

In [17]:
X=df.drop("Price",axis=1) # all column - target column
Y=df["Price"] #target column

In [18]:
!pip install scikit-learn

## splitting into Train and test

In [19]:
from sklearn.model_selection import train_test_split

# train_test_split(input,output,traing percent of data  (80%) (OR) testing percent of data(20%))

In [20]:
train_test_split(X,Y,test_size=0.2,random_state=23)

[       SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 20198        2169         2          3             1       1988
 34103        2568         3          2             2       1977
 40179        1339         3          3             1       1958
 34586        2716         2          1             1       1978
 30725        2307         3          1             1       1974
 ...           ...       ...        ...           ...        ...
 9704         2788         4          3             2       1986
 11190        2557         5          1             2       2004
 26569        2344         3          2             1       1961
 9256         1105         5          2             2       2008
 41555        2248         2          3             3       2020
 
 [40000 rows x 5 columns],
        SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt
 49466        1055         3          2             1       1969
 11621        1754         4          3             1       1

In [28]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=23)

In [29]:
X_train.shape

(40000, 5)

In [30]:
X_test.shape

(10000, 5)

In [31]:
Y_train.shape

(40000,)

In [32]:
Y_test.shape

(10000,)

## Alogorithmns
  - knn,linear regression,svm,decsion tree

# KNN

In [33]:

from sklearn.neighbors import KNeighborsRegressor     #KNeighborsRegressor is like a "class",we cant use it directly if it has 'capital letters' in it. 
                                                       #we create a object for using it ex:knn is a object, should be created.

In [34]:
#Evaluate how knn is working

from sklearn.metrics import mean_squared_error,r2_score

In [35]:
knn=KNeighborsRegressor()
knn.fit(X_train,Y_train)  #"fit" to make it learn 
Y_pred=knn.predict(X_test)
print(np.sqrt(mean_squared_error(Y_test,Y_pred)))

54247.93901533543


In [36]:
mean_squared_error(Y_test,Y_pred)

2942838887.4115524

In [37]:
np.sqrt(mean_squared_error(Y_test,Y_pred))

54247.93901533543

# LINEAR REGRESSION

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
lr=LinearRegression()
lr.fit(X_train,Y_train)  #"fit" to make it learn 
Y_pred=lr.predict(X_test)
print(np.sqrt(mean_squared_error(Y_test,Y_pred)))

49403.976927995944


# SUPORT VECTOR REGRESSION

In [40]:
from sklearn.svm import SVR

sv=SVR()
sv.fit(X_train,Y_train)  #"fit" to make it learn 
Y_pred=sv.predict(X_test)
print(np.sqrt(mean_squared_error(Y_test,Y_pred)))

# DECESION TREE

In [41]:
from sklearn.tree import DecisionTreeRegressor

In [42]:
dt = DecisionTreeRegressor()
dt.fit(X_train,Y_train)  #"fit" to make it learn 
Y_pred=dt.predict(X_test)
print(np.sqrt(mean_squared_error(Y_test,Y_pred)))

72388.19870344126


### Testing prediction model of house price

check logistic regression model

In [43]:
df.head(2)

SquareFeet  Bedrooms  Bathrooms  Neighborhood  YearBuilt          Price
0        2126         4          1             1       1969  215355.283618
1        2459         3          2             1       1980  195014.221626

In [44]:
lr.predict([[2750,6,2,3,1947]])[0]

C:\Users\saile\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


312775.3381191607

In [45]:
lr.intercept_

27719.428600465006

In [46]:
lr.coef_

array([  99.31308607, 5168.85659283, 2625.12603247,  752.26187692,
        -13.64933459])

In [47]:
#Pattern of House price prediction using Linear Regresssion
sqft = 2750
bed = 6
bath = 2
nb = 3
year = 1947
price = 99.31308607 * sqft +  5168.85659283 *bed + 2625.12603247*bath +752.26187692* nb -13.64933459 * year + 27719.4286004623
print(price)


312775.33809891227


### pickling

In [48]:
import pickle

In [49]:
pickle.dump(lr,open("lr.pkl","wb"))   ##writing as a binary format

In [50]:
model = pickle.load(open("lr.pkl","rb"))

In [51]:
model.predict([[2750,4,2,2,1998]])

C:\Users\saile\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([300989.24699266])

In [52]:
model.predict([[2126,4,1,1,1969]])

C:\Users\saile\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([236036.32407558])